name: Doxygen GitHub Pages Deploy Action
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: './src/'
          doxyfile-path: './docs/html'
          enable-latex: true
